name: Bug report
description: Something is not working (for everyone)
title: "Concise description of the issue"
labels: ["bug", "triage"]
body:
  - type: markdown
    value: "Thanks for taking the time to fill out this bug! If you need real-time help, join us on Discord."
